### ISSUE TITLE
The dimension of output of lstm dense2 is not the same as y

### ISSUE THREAD

**Issue by JianHangChen** [harvitronix/five-video-classification-methods#46] opened 2017-11-20 01:41 UTC
Here I run your newest version of lstm. I cannot get the training file running. The only difference is tensorflow version 1.4(maybe this is the problem?)

```
Loading LSTM model.
<keras.models.Sequential object at 0x7f2bbb497860>
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
lstm_1 (LSTM)                (None, 40, 2048)          33562624  
_________________________________________________________________
flatten_1 (Flatten)          (None, 81920)             0         
_________________________________________________________________
dense_1 (Dense)              (None, 512)               41943552  
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 101)               51813     
=================================================================
Total params: 75,557,989
Trainable params: 75,557,989
Non-trainable params: 0
_________________________________________________________________
None
Traceback (most recent call last):
  File "train.py", line 114, in <module>
    main()
  File "train.py", line 111, in main
    load_to_memory=load_to_memory, batch_size=batch_size, nb_epoch=nb_epoch)
  File "train.py", line 73, in train
    epochs=nb_epoch)
  File "/home/jhccc/tensorflow/lib/python3.5/site-packages/keras/models.py", line 960, in fit
    validation_steps=validation_steps)
  File "/home/jhccc/tensorflow/lib/python3.5/site-packages/keras/engine/training.py", line 1574, in fit
    batch_size=batch_size)
  File "/home/jhccc/tensorflow/lib/python3.5/site-packages/keras/engine/training.py", line 1411, in _standardize_user_data
    exception_prefix='target')
  File "/home/jhccc/tensorflow/lib/python3.5/site-packages/keras/engine/training.py", line 153, in _standardize_input_data
    str(array.shape))
**ValueError: Error when checking target: expected dense_2 to have shape (None, 101) but got array with shape (8596, 1)**


```

**Comment by JianHangChen** [comment] 2017-11-20 01:43
I print the size of training and testing:

**Loading 8596 samples into memory for training.
(8596, 40, 2048)
Loading 3418 samples into memory for testing.
(3418, 40, 2048)**

**Comment by harvitronix** [comment] 2017-11-20 01:49
I'm having a hard time reproducing this issue. This is after a fresh pull from the repo? Can you show me your settings? (Lines 86+ in `train.py`)

Did you extract features for all 101 classes using `extract_features.py`?

**Comment by harvitronix** [comment] 2017-11-20 05:13
After upgrading to TensorFlow 1.4 and Keras 2.1.1, I am now seeing a similar error. :(

```
ValueError: Error when checking target: expected dense_2 to have shape (None, 10) but got array with shape (32, 1)
```

**Comment by harvitronix** [comment] 2017-11-20 05:17
@JianHangChen It seems this can be fixed by changing the loss function from `categorical_crossentropy` to `sparse_categorical_crossentropy`. Please let me know if this fixes the issue for you as well.

**Comment by harvitronix** [comment] 2017-11-20 05:44
It actually looks like you found a significant bug. I've fixed the encoding of the Y value to make it one-hot again, and so `categorical_crossentropy` is the right loss function.

Just pushed the update to master.

Thank you!

**Closed by harvitronix** 2017-11-20 05:44 UTC
